---
blank_issues_enabled: true
contact_links:
  - name: ðŸ¤” Questions and Help
    url: https://github.com/AstroSteveo/k8s-infra/discussions
    about: Ask questions and get help from the community
  - name: ðŸ› Bug Reports
    url: >-
      https://github.com/AstroSteveo/k8s-infra/issues/new?template=bug_report.md
    about: Report bugs and issues with the infrastructure
